# Generated by Django 3.1.1 on 2020-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200906_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('dob', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('work', models.TextField()),
                ('obj', models.TextField()),
                ('awards', models.TextField()),
                ('c_name', models.CharField(max_length=255)),
                ('i_name', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('cgpa', models.CharField(max_length=4)),
                ('s_skill', models.TextField()),
                ('l_skill', models.TextField()),
                ('t_skill', models.TextField()),
            ],
        ),
    ]
