# Generated by Django 2.1.3 on 2020-09-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_auto_20200924_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvmodel',
            old_name='hobbies',
            new_name='interest',
        ),
    ]
