# Generated by Django 3.0.7 on 2020-10-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200908_2332'),
        ('jobsapp', '0003_auto_20200924_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('board1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('attempted1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gpa1', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('board2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('attempted2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gpa2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('board3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('attempted3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gpa3', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('board4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('attempted4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gpa4', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('department5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('passing5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cgpa5', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('department6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('passing6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cgpa6', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('institute7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('department7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('passing7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cgpa7', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
